### PR TITLE
fix: package-json.lock files are generated even if npm is not the package manager

### LINKED ISSUE #113: package-lock.json files are generated if they don't exist
### What happened?

Same fix as in https://github.com/trustification/exhort-javascript-api/pull/151

Do not generate the package-lock.json file if it doesn't exist. Fail and ask the user to generate it.

The extension should not assume any project with package.json file is using npm

### Please provide runtime information.

Any Javascript/Typescript project not using npm

### Relevant log output

```shell

```

### How can this issue be reproduced?

_No response_

### PR DESCRIPTION
**Pull request by ruromero**
## Description

This fix #113 
I also took the opportunity to:
* make system calls using an array of strings 
* remove unused and commented code
* Add TODOs for future work
* Move some hardcoded strings into constants
* Refactor the provider to be instantiated with the path
* Use `Path` instead of `Paths`
* Use a common functionality for accessing Environment variables and System properties: Prefer properties over EnvVars
* Implement componentAnalysis with a file path

**Related issue (if any):** fixes #issue_number_goes_here

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

### CODE REVIEW

File: src/main/java/com/redhat/exhort/Api.java [hunk 1]
```diff
@@ -99,15 +99,15 @@ public int hashCode() {
...
    * Use for creating a component analysis deserialized Json report for a given type and content.
    *
-   * @param manifestType the type of the manifest, i.e. {@code pom.xml}
+   * @param manifest the path of the manifest, example {@code /path/to/pom.xml}
    * @param manifestContent a byte array of the manifest's content
    * @return the deserialized Json report as an AnalysisReport wrapped in a CompletableFuture
    * @throws IOException when failed to load the manifest content
    */
-  CompletableFuture<AnalysisReport> componentAnalysis(String manifestType, byte[] manifestContent)
+  CompletableFuture<AnalysisReport> componentAnalysis(String manifestType, byte[] manifestConten)
```
Comment (Strum355) [inline src/main/java/com/redhat/exhort/Api.java:107]:
```suggestion
  CompletableFuture<AnalysisReport> componentAnalysis(String manifestType, byte[] manifestContent)
```

File: src/main/java/com/redhat/exhort/providers/GoModulesProvider.java [hunk 2]
```diff
@@ -48,91 +47,49 @@
...
+      throw new IllegalArgumentException(
+          "The provided manifest is not a regular file: " + manifest);
     }
-    return sbom;
-  }
-
-  private PackageURL getRoot(String DependenciesGolang) {
-    return null;
+    if (!Files.exists(manifest)) {
+      throw new IllegalArgumentException("Missing required go.mod file: " + manifest.toString());
```
Comment (Strum355) [inline src/main/java/com/redhat/exhort/providers/GoModulesProvider.java:84]: `Files.exists` check should probably come before `Files.isRegularFile`. `Files.isRegularFile` will return false if the file doesnt exist, which means we would never surface "Missing required go.mod file" if the file doesnt exist

Comment (ruromero) [reply src/main/java/com/redhat/exhort/providers/GoModulesProvider.java]: nice catch, thanks

File: src/main/java/com/redhat/exhort/tools/Operations.java [hunk 3]
```diff
@@ -121,49 +127,34 @@ public static String runProcessGetOutput(Path dir, final String... cmdList) {
...
-      if (sb.toString().trim().equals("")) {
-        inputStream = process.getErrorStream();
-        reader = new BufferedReader(new InputStreamReader(inputStream));
-        while ((line = reader.readLine()) != null) {
-          sb.append(line);
-          if (!line.endsWith(System.lineSeparator())) {
-            sb.append("\n");
-          }
-        }
+      // TODO: This should throw an exception if the process fails
```
Comment (Strum355) [inline src/main/java/com/redhat/exhort/tools/Operations.java:149]: Do you want to do this in this PR or a later one?

File: src/main/java/com/redhat/exhort/utils/Environment.java [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+    return Optional.ofNullable(System.getProperty(name))
+        .or(() -> Optional.ofNullable(System.getenv(name)))
+        .orElse(defaultValue);
+  }
+
+  public static final String get(String name) {
+    return get(name, null);
+  }
+
+  public static final boolean getBoolean(String key, Boolean defaultValue) {
```
Comment (Strum355) [inline src/main/java/com/redhat/exhort/utils/Environment.java:34]: non-blocking nit: should `defaultValue` be `Boolean` vs primitive type? If someones going to pass `null` Id imagine they might as well pass `false` so things are clearer at call-site

**Review by Strum355 — APPROVED** [review]
LGTM, some small non-blocking comments

File: src/main/java/com/redhat/exhort/utils/Environment.java (hunk 4 above)
Comment (ruromero) [reply src/main/java/com/redhat/exhort/utils/Environment.java:34]: You're right. That's a refactoring leftover. Thanks
