### PR TITLE
fix: parse go env in json format

### LINKED ISSUE #166: [go] `go env` output is different in windows than unix
### What happened?

The purls are not properly parsed in Windows due to the different output of the `go env` command

### Please provide runtime information.

Windows / Linux
Go 1.24
JRE 17

### Relevant log output

```shell
$ go env       
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/rromerom/Library/Caches/go-build'
GOENV='/Users/rromerom/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/rromerom/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/rromerom/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/Users/rromerom/Tools/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/rromerom/Tools/go/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.5'
GCCGO='gccgo'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/0g/kw16tkc94tb47c4mk6r4ct7c0000gn/T/go-build3167483895=/tmp/go-build -gno-record-gcc-switches -fno-common'

> go env
set AR=ar
set CC=gcc
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_ENABLED=0
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set CXX=g++
set GCCGO=gccgo
set GO111MODULE=
set GOAMD64=v1
set GOARCH=amd64
set GOAUTH=netrc
set GOBIN=
set GOCACHE=C:\Users\Administrator\AppData\Local\go-build
set GOCACHEPROG=
set GODEBUG=
set GOENV=C:\Users\Administrator\AppData\Roaming\go\env
set GOEXE=.exe
set GOEXPERIMENT=
set GOFIPS140=off
set GOFLAGS=
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=C:\Users\ADMINI~1\AppData\Local\Temp\2\go-build2302477238=/tmp/go-build -gno-record-gcc-switches
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
set GOMOD=NUL
set GOMODCACHE=C:\Users\Administrator\go\pkg\mod
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\Administrator\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=C:\Program Files\Go
set GOSUMDB=sum.golang.org
set GOTELEMETRY=local
set GOTELEMETRYDIR=C:\Users\Administrator\AppData\Roaming\go\telemetry
set GOTMPDIR=
set GOTOOLCHAIN=auto
set GOTOOLDIR=C:\Program Files\Go\pkg\tool\windows_amd64
set GOVCS=
set GOVERSION=go1.24.5
set GOWORK=
set PKG_CONFIG=pkg-config
```

### How can this issue be reproduced?

_No response_

### PR DESCRIPTION
**Pull request by ruromero**
## Description

Use the `json` format for the `go env` command to make it OS agnostic

**Related issue (if any):** fixes #166 

## Checklist

- [x] I have followed this repository's contributing guidelines.
- [x] I will adhere to the project's code of conduct.

### CODE REVIEW

File: src/main/java/com/redhat/exhort/providers/GoModulesProvider.java [hunk 1]
```diff
@@ -379,45 +381,39 @@ private static List<String> collectAllDirectDependencies(List<String> targetLine
...
-    } else {
-      envValue = goEnvironmentVariables.substring(beginIndex).substring(0, endOfLineIndex);
+  private Map<String, String> getGoEnvironmentVariables() {
+    String goEnvironmentVariables =
+        Operations.runProcessGetOutput(null, goExecutable, "env", "--json");
+    JsonNode tree;
+    try {
+      tree = new ObjectMapper().readTree(goEnvironmentVariables);
+    } catch (JsonProcessingException e) {
+      log.warning(String.format("Failed to parse go environment variables: %s", e.getMessage()));
```
Comment (Strum355) [inline src/main/java/com/redhat/exhort/providers/GoModulesProvider.java:405]: Any reason we log instead of throw?

**Review by Strum355 — APPROVED** [review]

File: src/main/java/com/redhat/exhort/providers/GoModulesProvider.java (hunk 1 above)
Comment (ruromero) [reply src/main/java/com/redhat/exhort/providers/GoModulesProvider.java]: you are right
